project:
  type: website
  resources:
    - data/

website:
  title: "WNBA & NBA Leaders"
  navbar:
    left:
      - href: index.qmd
        text: Exploration
      - href: graphs.qmd
        text: Graphs
      - href: project-overview.qmd
        text: Project Overview
      - href: story.qmd
        text: Story
      - href: about.qmd
        text: About

format:
  html:
    theme: flatly
    toc: false
